Q1.
Load the dataset and display the first five records.

In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression

from sklearn.metrics import accuracy_score, confusion_matrix

In [4]:
import pandas as pd
df = pd.read_csv("netflix.csv")

df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

Q2.
Determine the number of rows and columns in the dataset.

In [5]:
print("Rows and Columns:", df.shape)

Rows and Columns: (750, 10)

Q3.
Display all column names.

In [6]:
print(df.columns)

Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')

Q4.
Identify numerical and categorical features.

In [7]:
print("Numerical Features:")
print(df.select_dtypes(include=['int64','float64']).columns)

print("\nCategorical Features:")
print(df.select_dtypes(include=['object']).columns)

Numerical Features:
Index(['UserID', 'Age', 'WatchHoursPerWeek', 'DevicesUsed', 'AdClicks',
       'MonthlySpend'],
      dtype='object')

Categorical Features:
Index(['Gender', 'SubscriptionType', 'FavoriteGenre', 'SubscriptionRenewed'], dtype='object')

Q5.
Check whether the dataset contains missing values.

In [8]:
print(df.isnull().sum())

UserID                 0
Age                    0
Gender                 0
SubscriptionType       0
WatchHoursPerWeek      0
DevicesUsed            0
FavoriteGenre          0
AdClicks               0
MonthlySpend           0
SubscriptionRenewed    0
dtype: int64

Q6.
Calculate the average age of users.

In [9]:
print(df["Age"].mean())

41.824

Q7.
Determine the average watch hours per week.

In [10]:
print(df["WatchHoursPerWeek"].mean())

14.236

Q8.
Find the average monthly spending of users.

In [11]:
print(df["MonthlySpend"].mean())

689.9053333333334

Q9.
Count the number of users in each subscription category.

In [12]:
print(df["SubscriptionType"].value_counts())

SubscriptionType
Basic      342
Premium    279
VIP        129
Name: count, dtype: int64

Q10.
Determine the percentage of users who renewed their subscriptions.

In [13]:
renewal_percentage = (
    (df["SubscriptionRenewed"] == "Yes").mean() * 100
)

print("Renewal Percentage:", renewal_percentage)

Renewal Percentage: 46.266666666666666

Q11.
Convert categorical features into numerical form.

In [14]:
le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,0,0,23,5,1,13,353,0
1,1002,55,1,0,9,4,2,14,317,1
2,1003,49,1,0,8,3,1,16,309,0
3,1004,39,0,1,19,5,2,45,833,1
4,1005,38,0,1,23,5,5,24,804,1

Q12.
Define the feature set (X) and target variable (y) for subscription renewal prediction.

In [15]:
X = df.drop("SubscriptionRenewed", axis=1)

y = df["SubscriptionRenewed"]

Q13.
Split the dataset into training and testing sets

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

Q14.
Train a Decision Tree model to predict whether a user will renew their subscription

In [17]:
dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

Q15.
Evaluate the model using accuracy.

In [18]:
y_pred_dt = dt.predict(X_test)

acc_dt = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy:", acc_dt)

Decision Tree Accuracy: 0.5666666666666667

Q16.
Generate and interpret the confusion matrix

In [19]:
cm = confusion_matrix(y_test, y_pred_dt)

print(cm)

[[50 32]
 [33 35]]

Q17.
Train a KNN classifier with K = 5.

In [20]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

Q18.
Compare the accuracy of KNN with the Decision Tree model.

In [21]:
acc_knn = accuracy_score(y_test, y_pred_knn)

print("Decision Tree Accuracy:", acc_dt)
print("KNN Accuracy:", acc_knn)

Decision Tree Accuracy: 0.5666666666666667
KNN Accuracy: 0.6

Q19.
Train a Linear Regression model to predict monthly spending.

In [22]:
X_reg = df.drop("MonthlySpend", axis=1)

y_reg = df["MonthlySpend"]

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg, y_reg,
    test_size=0.2,
    random_state=42
)

lr = LinearRegression()

lr.fit(X_train_reg, y_train_reg)

LinearRegression()

Q20.
Predict the monthly spending for a new user and interpret the result.

In [23]:
new_user = [X_reg.iloc[0]]

prediction = lr.predict(new_user)

print("Predicted Monthly Spend:", prediction[0])

Predicted Monthly Spend: 391.3851628098203

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

Business Questions

1.Which factors appear to influence subscription renewal the most?

In [26]:
importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': dt.feature_importances_
})

print(importance.sort_values(by='Importance', ascending=False))

             Feature  Importance
8       MonthlySpend    0.217700
0             UserID    0.186622
1                Age    0.171988
4  WatchHoursPerWeek    0.160064
7           AdClicks    0.128323
6      FavoriteGenre    0.057307
5        DevicesUsed    0.054726
2             Gender    0.019920
3   SubscriptionType    0.003350

Monthly Spend

2. Why is subscription renewal a classification problem?

 answer:

Subscription renewal is a classification problem because the target variable has discrete categories (Yes or No). The model predicts which class a user belongs to.

3. Why is monthly spending a regression problem?

 answer:

Monthly spending is a regression problem because it is a continuous numerical value. The goal is to predict an amount rather than a category.



5. How could the platform use these predictions to improve customer retention?

 answer:

Netflix can identify users who are likely not to renew and target them with personalized recommendations, discounts, special offers, or engagement campaigns. This can help reduce customer churn and improve retention.

4. Which algorithm performed better for renewal prediction?

In [25]:
print(acc_dt)
print(acc_knn)

0.5666666666666667
0.6

 KNN > DT:

KNN achieved higher accuracy and therefore performed better.